import { z } from 'zod';
import { createToolCallAccuracyScorerCode } from '@mastra/evals/scorers/code';
import { createCompletenessScorer } from '@mastra/evals/scorers/code';
import { createScorer } from '@mastra/core/scores';

export const toolCallAppropriatenessScorer = createToolCallAccuracyScorerCode({
  expectedTool: 'translateTool',
  strictMode: false,
});

export const completenessScorer = createCompletenessScorer();

// LinguaFlash custom translation scorer
export const translationScorer = createScorer({
  name: 'Translation Accuracy',
  description: 'Evaluates the translation accuracy and linguistic quality produced by LinguaFlash.',
  type: 'agent',
  judge: {
    model: 'google/gemini-2.5-pro',
    instructions: `
      You are a professional linguist and translation evaluator for the LinguaFlash translator agent.
      Your goal is to assess if the translated output accurately conveys the meaning of the original text while maintaining tone, grammar, and context.
      Consider:
      - Semantic accuracy (meaning preserved)
      - Grammar and fluency in the target language
      - Tone and style consistency (formal/informal, context)
      - Faithfulness to the original text without unnecessary additions or omissions
      Return a JSON object that rates translation accuracy and confidence.
    `,
  },
})
  .preprocess(({ run }) => {
    const sourceText = (run.input?.inputMessages?.[0]?.content as string) || '';
    const translatedText = (run.output?.[0]?.content as string) || '';
    return { sourceText, translatedText };
  })
  .analyze({
    description: 'Evaluate translation quality and adequacy between source and translated text.',
    outputSchema: z.object({
      accurate: z.boolean(),
      natural: z.boolean(),
      confidence: z.number().min(0).max(1).default(1),
      explanation: z.string().default(''),
    }),
    createPrompt: ({ results }) => `
      You are evaluating a translation generated by LinguaFlash.

      Source text:
      """
      ${results.preprocessStepResult.sourceText}
      """

      Translated text:
      """
      ${results.preprocessStepResult.translatedText}
      """

      Tasks:
      1) Determine if the translation accurately conveys the original meaning.
      2) Check if it reads naturally and fluently in the target language.
      3) Identify if tone and style are consistent with the context.

      Return JSON:
      {
        "accurate": boolean,
        "natural": boolean,
        "confidence": number, // 0-1
        "explanation": string
      }
    `,
  })
  .generateScore(({ results }) => {
    const r = (results as any)?.analyzeStepResult || {};
    if (!r.accurate) return 0;
    const base = r.natural ? 0.8 : 0.6;
    return Math.max(0, Math.min(1, base + 0.2 * (r.confidence ?? 1)));
  })
  .generateReason(({ results, score }) => {
    const r = (results as any)?.analyzeStepResult || {};
    return `Translation accuracy evaluation: accurate=${r.accurate ?? false}, natural=${r.natural ?? false}, confidence=${r.confidence ?? 0}. Score=${score}. ${r.explanation ?? ''}`;
  });

export const scorers = {
  toolCallAppropriatenessScorer,
  completenessScorer,
  translationScorer,
};
